FROM golang:1.11-stretch
RUN apt-get update && apt-get install -y vim tree lsof
ENV GOPATH=/home/eacred/go
ENV PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$GOPATH/bin
ENV ECRSRC_PATH=$GOPATH/src/github.com/Eacred/eacrdata/
ENV GO111MODULE=on
RUN useradd eacred -m -s /bin/bash && chown -R eacred:eacred /home/eacred
WORKDIR $ECRSRC_PATH
RUN chown -R eacred:eacred $GOPATH
USER eacred
# since we might be rebulding often we need to cache this module layer
# otherwise docker will detect changes everytime and re-download everything again
COPY go.* $ECRSRC_PATH
RUN go mod download
COPY . $ECRSRC_PATH
RUN go build
CMD /bin/bash
ENTRYPOINT ./eacrdata
# Note: when building the --squash flag is an experimental feature as of Docker 18.06
# docker build --squash -t eacred/eacrdata .
# running
# docker run -ti --rm eacred/eacrdata
# or if attaching source volume and developing interactively
# docker run -ti --entrypoint=/bin/bash -v ${PWD}:${PWD}:/home/eacred/go/src/github.com/Eacred/eacrdata --rm eacred/eacrdata