FROM golang:1.10-alpine3.8
RUN apk update && apk add vim tree lsof bash git gcc musl-dev
ENV GOPATH=/home/eacred/go
ENV PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$GOPATH/bin
ENV ECRSRC_PATH=$GOPATH/src/github.com/Eacred/eacrdata/
RUN adduser -s /bin/bash -D -h /home/eacred eacred && chown -R eacred:eacred /home/eacred
WORKDIR $ECRSRC_PATH
# since we might be rebulding often we need to cache this module layer
# otherwise docker will detect changes everytime and re-download everything again
RUN go get -u -v github.com/golang/dep/cmd/dep
COPY Gopkg* $ECRSRC_PATH
# we perform a vendor ensure here to speed up future layers
RUN touch main.go && dep ensure -vendor-only
COPY . $ECRSRC_PATH
RUN chown -R eacred:eacred $GOPATH
USER eacred
RUN dep ensure && dep ensure --vendor-only && go build
CMD /bin/bash

ENTRYPOINT ./eacrdata
# Note: when building the --squash flag is an experimental feature as of Docker 18.06
# docker build --squash -t eacred/eacrdata .
# running
# docker run -ti --rm eacred/eacrdata
# or if attaching source volume and developing interactively
#  docker run -ti --entrypoint=/bin/bash -v ${PWD}:/home/eacred/go/src/github.com/Eacred/eacrdata --rm eacred/eacrdata